development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://hxkcrffyyolvag:bfd8e3e8570e84dbcd36744287eb55758411854c22ef7b32ab2813257a7494f6@ec2-23-21-86-22.compute-1.amazonaws.com:5432/d21fuausbghsic
  channel_prefix: myfirstapp_production
